### ISSUE TITLE
Integrate with a running daemon

### ISSUE THREAD

**Issue by Dignifiedquire** [haadcode/anonymous-networks#1]
At the moment there are errors thrown when I already have a daemon running, but if I'm trying to run multiple ipfs apps in parallel and they all want to bring their own daemon this present an issue for me.

**Comment by haadcode** [comment]
Thanks for filing the issue!

At the moment, the application shouldn't start if IPFS daemon is already running and you should see an error message in the logs: "IPFS daemon already running! Please make sure ipfs daemon is not running." and anonymous-networks should exit gracefully.

If this is not the case, can you provide the log (debug.log) and/or any other details as to how it fails?

**Comment by Dignifiedquire** [comment]
That error works, but my point is that it should not throw an error, but instead connect to the running instance, as for example this stops me from running station and this at the same time.

**Comment by haadcode** [comment]
Got it and agreed. Will put it on the todo list.

**Comment by haadcode** [comment]
Should be fixed with c3ebea089ad2d95944516d54888344292513b2af
